server:
  port: 8080
  context-path: /blog/     #名字前面一定要加/ 不然启动会报错
  tomcat:
    basedir: targer/tomcat
    accesslog:
      enabled: true

#数据库配置
spring:
  datasource:
    url :  jdbc:mysql://192.168.201.1:3306/Shop??useUnicode=true&characterEncoding=utf-8
    name :  Shop
    username : root
    password : 123456
    # 使用druid数据源
    # type :  com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    filters : stat
    maxActive : 20
    initialSize : 1
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20


  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/static/

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 0
      max-wait: -1
      min-idle: 0
    timeout: 20000


# mybatis 配置
mybatis:
  mapperLocations: classpath:com/blog/mapper/*.xml
  typeAliasesPackage: com.blog.model

#自定义属性
USER_SESSION: USER_SESSION
logging:
  level: debug
  path: classpath:logback-spring.xml

security:
  basic:
    enabled: false